#!/bin/bash

################################################################
#
# GLIMPSES toolkit
# Copyright (c) 2008,2009 Jaswanth Sreeram, Ashwini Bhagwat
#				  Sarang Ozarde
# 
# glimpses: Main executable that invokes the profiler/visualizer.
# 
# Note: Set the JAVA_HOME environment variable before running this.
#
################################################################

TOPLEVEL_DIR=`pwd`
PREFUSE_DIR=$TOPLEVEL_DIR/prefuse-beta
WORKBENCH_DIR=$TOPLEVEL_DIR/WorkBench

export LD_BIND_NOW=1

if [ "$JAVA_HOME" = "" ] ; then
    echo "Glimpses : Please set the JAVA_HOME environment variable to the location of your Java installation"
    exit 1
fi

export CLASSPATH=.:$JAVA_HOME/lib:$PREFUSE_DIR/lib:$PREFUSE_DIR/build/lib:$PREFUSE_DIR/build:$PREFUSE_DIR/build/prefuse/classes
echo "[Glimpses] : Using classpath:"
echo $CLASSPATH
cd $PREFUSE_DIR/build/demos/classes
$JAVA_HOME/bin/java -Xss100M prefuse/demos/GraphView $1
cd -;
